version: '2'

networks:
  txmnet:

services:
  node1:
    image: dstxmanager
    hostname: node1.nodes.local
    ports:
      - 8081:8080
    networks:
      - txmnet
    environment:
      - SHARD=0

  node2:
    image: dstxmanager
    hostname: node2.nodes.local
    ports:
      - 8082:8080
    networks:
      - txmnet
    environment:
      - SHARD=0

  node3:
    image: dstxmanager
    hostname: node3.nodes.local
    ports:
      - 8083:8080
    networks:
      - txmnet
    environment:
      - SHARD=0

  node4:
    image: dstxmanager
    hostname: node4.nodes.local
    ports:
      - 8084:8080
    networks:
      - txmnet
    environment:
      - SHARD=1

  node5:
    image: dstxmanager
    hostname: node5.nodes.local
    ports:
      - 8085:8080
    networks:
      - txmnet
    environment:
      - SHARD=1

  node6:
    image: dstxmanager
    hostname: node6.nodes.local
    ports:
      - 8086:8080
    networks:
      - txmnet
    environment:
      - SHARD=1